name: brebit
description: An Awesom breaking habit application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # Check that you have this dependency (added in the previous step)
  firebase_core: ^1.3.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^8.1.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.2.0
  firebase_messaging: ^10.0.1

  provider: ^5.0.0
  rxdart: ^0.24.1

  flutter_local_notifications: ^5.0.0+1


  http_parser: ^4.0.0
  #  dio: ^3.0.10
  #  dio_cookie_manager: ^1.0.0
  #  cookie_jar: ^1.0.1

  shared_preferences: ^2.0.6
  cached_network_image: ^2.3.3
  flutter_absolute_path: ^1.0.6
  firebase_dynamic_links: ^2.0.6

  flutter_multiselect: ^0.5.1

  notification_permissions: ^0.4.8
  app_settings: ^4.1.0

  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.12.2

  image_cropper: ^1.3.1
  photo_view: ^0.10.3
  transparent_image: ^1.0.0
  flutter_svg: ^0.22.0
  image: ^3.0.2
  image_size_getter: ^0.2.1

  flutter_advanced_switch: ^2.1.0
  flutter_sticky_header: ^0.5.0
  page_transition: ^1.1.7+6
  modal_bottom_sheet: ^1.0.0+1
  flutter_picker: ^2.0.1
  flutter_signin_button: ^2.0.0

  introduction_screen: ^1.0.7
  dots_indicator: ^1.2.0

  url_launcher: ^6.0.2
  photo_manager: ^1.3.1
  sliding_up_panel: ^1.0.2
  path_provider: ^2.0.1
  flutter_keyboard_visibility: ^5.0.0
  #  wechat_assets_picker: ^5.1.2
  image_picker: ^0.7.4
  http: ^0.13.1
  uuid: ^3.0.4
  multi_image_picker: ^4.8.00
  time_machine: ^0.9.16
  permission_handler: ^7.1.0
  flutter_easyloading: ^3.0.0
  emojis: ^0.9.3
  flutter_html: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  flutter_native_splash:

flutter_native_splash:
  image: "assets/splash/logo.png"
  color: "65BDC0"
  android_disable_fullscreen: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/introduction/
    - assets/icon/
    - assets/steps/
    - assets/splash/
    - assets/images/
    - assets/explanation/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: futura
  #      fonts:
  #        - asset: fonts/futura/futura-medium.ttf
  #        - asset: fonts/futura/futura-book.ttf
  #          weight: 400
  #        - asset: fonts/futura/futura-light.ttf
  #          weight: 200
  #        - asset: fonts/futura/futura-heavy.ttf
  #          weight: 600
  #        - asset: fonts/futura/futura-extra-black.ttf
  #          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
