name: brebit
description: An Awesom breaking habit application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # Check that you have this dependency (added in the previous step)
  firebase_core: ^2.3.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^10.0.6

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^4.1.4
  google_sign_in: ^5.4.0
  sign_in_with_apple: ^4.1.0
  firebase_messaging: ^14.1.2
  firebase_dynamic_links: ^5.0.6

  provider: ^6.0.3
  rxdart: ^0.27.5

  flutter_local_notifications: ^12.0.4


  http_parser: ^4.0.1
  #  dio: ^3.0.10
  #  dio_cookie_manager: ^1.0.0
  #  cookie_jar: ^1.0.1

  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  #  flutter_absolute_path: ^1.0.6

  flutter_multiselect: ^1.0.0

  notification_permissions: ^0.6.1
  app_settings: ^4.1.0

  flutter_hooks: ^0.18.5
  hooks_riverpod: ^2.1.1

  image_cropper: ^3.0.1
  photo_view: ^0.14.0
  transparent_image: ^2.0.0
  flutter_svg: ^1.1.3
  image: ^3.1.0
  image_size_getter: ^2.1.2

  flutter_advanced_switch: ^3.0.1
  flutter_sticky_header: ^0.6.4
  page_transition: ^2.0.9
  modal_bottom_sheet: ^2.1.0
  flutter_picker: ^2.0.1
  flutter_signin_button: ^2.0.0

  introduction_screen: ^3.0.2
  dots_indicator: ^2.1.0

  url_launcher: ^6.0.2
  photo_manager: ^2.2.1
  sliding_up_panel: ^2.0.0
  path_provider: ^2.0.1
  flutter_keyboard_visibility: ^5.0.0
  #  wechat_assets_picker: ^5.1.2
  image_picker: ^0.8.5
  http: ^0.13.1
  uuid: ^3.0.4
  multi_image_picker: ^4.8.00
  time_machine: ^0.9.16
  permission_handler: ^10.0.0
  flutter_easyloading: ^3.0.0
  emojis: ^0.9.3
  flutter_launcher_icons: ^0.11.0
  confetti: ^0.7.0
  flutter_aws_s3_client: ^0.6.0
  flutter_math_fork: ^0.6.3+1

dependency_overrides:
  firebase_core_platform_interface: 4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  flutter_native_splash:

flutter_native_splash:
  image: "assets/splash/logo.png"
  color: "65BDC0"
  android_disable_fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/introduction/
    - assets/icon/
    - assets/steps/
    - assets/splash/
    - assets/images/
    - assets/explanation/
    - assets/app_icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: futura
  #      fonts:
  #        - asset: fonts/futura/futura-medium.ttf
  #        - asset: fonts/futura/futura-book.ttf
  #          weight: 400
  #        - asset: fonts/futura/futura-light.ttf
  #          weight: 200
  #        - asset: fonts/futura/futura-heavy.ttf
  #          weight: 600
  #        - asset: fonts/futura/futura-extra-black.ttf
  #          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages