name: Flutter iOS Build

on: [push]

env:
  flutter_version: '3.7.10'
jobs:
  build-iOS:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
          # arm64だとうまくいかない
          # architecture: arm64
          cache: true
      - run: flutter --version
      
#      - name: Remove podfile.lock
#        run: cd ios && rm -rf Podfile.lock
#
#      - name: update cocoapods
#        run: pod repo update
#
#      - name: flutter clean
#        run: flutter clean

      - name: Download Flutter packages
        run: flutter pub get

#       - name: Test
#         run: flutter test

      - name: Cocoapods setup for Build
        run: pod repo update
        working-directory: ./ios

      - name: Build
        run: flutter build ios --release --no-codesign
