name: Flutter iOS Build

on: [push]

jobs:
  build-iOS:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh 2.17.0

      - name: Download Flutter packages
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Build
        run: flutter build ios --release --no-codesign

      # # 成果物アップロード
      # - name: artifact upload
      #   uses: actions/upload-artifact@v2.2.0
      #   with:
      #     # 保存ファイル名（name.zip）
      #     name: ios
      #     # 保存するファイル
      #     path: ./build/ios/
      #     # 保存期間（日）
      #     retention-days: 1
