name: Flutter iOS Build

on: [push]

jobs:
  build-ios:
    needs: test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.18.0'
        channel: 'stable'
        cache: true
    - run: flutter pub get
    - run: flutter test
    # iOS Build
    - run: flutter build ios --release --no-codesign
    # 成果物アップロード
    - name: artifact upload
      uses: actions/upload-artifact@v2.2.0
      with:
        # 保存ファイル名（name.zip）
        name: ios
        # 保存するファイル
        path: ./build/ios/
        # 保存期間 (日)
        retention-days: 1
